### ISSUE TITLE
运行示例，报panic错误

### ISSUE THREAD

**Issue by tanglong1993** [akkagao/go2proto#1]
环境： windows
go： go version go1.10.3 windows/amd64

错误日志：

接口名称： User
2019/09/25 10:47:56 function:Createuser index:1 paramName:request
2019/09/25 10:47:56 function:Createuser index:1 paramType:Request
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x520ca8]

**Comment by akkagao** [comment]
你更新下go版本再试一下，我是在go 1.13 版本下开发的
go version go1.13 darwin/amd64

**Comment by akkagao** [comment]
我刚在mac上用 go version go1.10.3 darwin/amd64 版本测试没有问题的
你再试试，如果还有问题，你加下我QQ  870027589 我们讨论

![image](https://user-images.githubusercontent.com/15965699/66483885-8c592a00-ead8-11e9-9927-78631311a83b.png)

**Comment by tanglong1993** [comment]
谢谢，是版本的原因。
